### PR TITLE
Major Rewrite for Stability and Readability

### PR DESCRIPTION
**Pull request by KarlZeilhofer**
Hi, 

recently I've worked again on the code. I rewrote most of the code. We had major problems with the old code for large projects with many fields.  

Main difference:
* use more direct access to class members without unnecessary getters/setters. 
* use regular expressions for parsing the schematic file
* CSV separator is configurable
* update of all KiCad default fields
* allways export KiCad default fields
Further details can be found in the CHANGELOG.md

Some TODOs are still open, but I think this is now a major step forward. 

Would be nice, if you can test this version with your workflow. If you like this version, please merge the pull request. 

Greets, Karl

### CODE REVIEW

**Comment by BPJWES** [comment]
Hi,

Impressive work!

I have cloned your pull request to a local repository to evaluate it.

I will come back to you soon.


Regards,

Berjan Westerdijk

**Comment by KarlZeilhofer** [comment]
Great, thanks for your efforts!

**Comment by KarlZeilhofer** [comment]
I hope, soon I will rewrite the CSV reader/writer by using the CSV module, this would enable quotation marks, and therefore the allowed characters wouldn't be limited any more. Currently the separator must not be used...

**Comment by KarlZeilhofer** [comment]
Hi, 
I've released V18.0.2. This fixes an issue with parts on the root sheet, and supports now KiCad 5. 
Do you think you can merge it?
Greets, Karl

**Comment by BPJWES** [comment]
Hi,

I have used your changes 0333093 for a recent project I worked on using a relatively recent version of the KiCad nightlies (from March somewhere I recon). And I could not find any issues functionality wise.

I did find some other minor errors, but I will fix those in a later commit.

I'll check your latest changes tonight and will merge them asap.

Regards,

Berjan

**Comment by KarlZeilhofer** [comment]
Great! 
I released tonight a new tool for updating 3D models, perhaps you are interested in it: 
https://github.com/KarlZeilhofer/kicad-models-updater

**Pull request merged**
